"""DMD training for one Wan2.2 T2V-A14B noise expert.

Wan2.2-A14B uses separate high- and low-noise DiTs.  The DMD objective is the
same one used by :class:`VideoDmdTrainer`, but the generator trajectory and
fake-score target must respect the boundary between the experts:

* the high expert maps noise to a latent at the boundary timestep;
* the low expert starts from a boundary latent generated by a frozen,
  distilled high expert and maps it to x0.

This trainer deliberately delegates all boundary math to
``Wan22DMDFlowMatchingScheduler``.  Keeping it out of the trainer makes the
same formulas available to rollout, DMD score conversion, and fake-score
supervision without subtly diverging implementations.
"""

import copy
import os
from typing import Mapping, Optional

import torch
import torch.nn.functional as F
from loguru import logger
from safetensors.torch import load_file

from lightx2v_train.model_zoo import build_model
from lightx2v_train.runtime.parallel import apply_parallel
from lightx2v_train.runtime.sequence_parallel import broadcast_sequence_parallel_value
from lightx2v_train.schedulers.wan22_dmd_scheduler import Wan22DMDFlowMatchingScheduler
from lightx2v_train.utils.registry import TRAINER_REGISTER

from .dmd import VideoDmdTrainer


@TRAINER_REGISTER("wan22_a14b_dmd")
class Wan22A14BDmdTrainer(VideoDmdTrainer):
    """Expert-aware Wan2.2-A14B DMD trainer.

    ``training.student`` and ``training.fake`` retain the regular DMD
    ``train_type: lora|full`` contract.  Consequently the existing LoRA,
    FSDP2, sequence-parallel gradient synchronization, and distributed
    checkpoint paths are reused unchanged.
    """

    trainer_name = "wan22_a14b_dmd"
    allowed_model_names = {"wan2_2_t2v_a14b"}

    _EXPERT_ALIASES = {
        "high": "high_noise",
        "high_noise": "high_noise",
        "high_noise_model": "high_noise",
        "low": "low_noise",
        "low_noise": "low_noise",
        "low_noise_model": "low_noise",
    }
    _DEFAULT_STEPS = {
        "high_noise": (1000, 750),
        "low_noise": (500, 250),
    }

    def __init__(self, config):
        super().__init__(config)

        configured_expert = self.dmd_config.get(
            "expert",
            self.dmd_config.get("training_target", self.model_config.get("expert")),
        )
        self.expert = self._normalize_expert(configured_expert)
        self.boundary_timestep = int(
            self.dmd_config.get("boundary_timestep", self.dmd_config.get("boundary_step", self.num_train_timestep // 2))
        )
        if not 0 < self.boundary_timestep < self.num_train_timestep:
            raise ValueError(
                "training.dmd.boundary_timestep must be strictly between 0 and "
                f"num_train_timestep={self.num_train_timestep}, got {self.boundary_timestep}."
            )

        # ``VideoDmdTrainer`` supplies generic four-step defaults.  A14B has
        # two steps per expert, so replace that default only when the config
        # did not explicitly provide a trajectory.
        if "denoising_step_list" not in self.dmd_config:
            self.denoising_step_list = list(self._DEFAULT_STEPS[self.expert])
            self.num_inference_steps = len(self.denoising_step_list)
        self._validate_expert_steps(self.denoising_step_list, self.expert, name="denoising_step_list")

        self.high_prefix_config = copy.deepcopy(self.dmd_config.get("high_prefix", {}))
        default_prefix_steps = self._DEFAULT_STEPS["high_noise"]
        self.high_prefix_steps = list(self.high_prefix_config.get("denoising_step_list", default_prefix_steps))
        self._validate_expert_steps(self.high_prefix_steps, "high_noise", name="high_prefix.denoising_step_list")

        configured_model_expert = self.model_config.get("expert")
        if configured_model_expert is not None and self._normalize_expert(configured_model_expert) != self.expert:
            raise ValueError(
                f"model.expert={configured_model_expert!r} does not match training.dmd.expert={self.expert!r}."
            )
        if not self.warp_denoising_step:
            raise ValueError("Wan2.2 A14B DMD requires training.dmd.warp_denoising_step=true.")
        if self.infer_every_iters is not None:
            raise ValueError(
                "wan22_a14b_dmd trains one expert at a time, so generic single-model training inference is not valid. "
                "Set inference.method=none and evaluate checkpoints with the complete Wan2.2 high+low inference pipeline."
            )

        self.high_prefix_model = None

    @classmethod
    def _normalize_expert(cls, expert):
        key = "" if expert is None else str(expert).strip().lower()
        if key not in cls._EXPERT_ALIASES:
            raise ValueError(
                f"Wan2.2 A14B DMD requires training.dmd.expert='high' or 'low', got {expert!r}."
            )
        return cls._EXPERT_ALIASES[key]

    def _validate_expert_steps(self, steps, expert, name):
        steps = [int(step) for step in steps]
        if not steps:
            raise ValueError(f"training.dmd.{name} must contain at least one timestep.")
        expected_start = self.num_train_timestep if expert == "high_noise" else self.boundary_timestep
        if steps[0] != expected_start:
            raise ValueError(
                f"training.dmd.{name} must start at {expected_start} for the {expert} rollout, got {steps[0]}."
            )
        if any(left <= right for left, right in zip(steps, steps[1:])):
            raise ValueError(f"training.dmd.{name} must be strictly decreasing, got {steps}.")
        if expert == "high_noise":
            invalid = [step for step in steps if not self.boundary_timestep < step <= self.num_train_timestep]
            expected = f"({self.boundary_timestep}, {self.num_train_timestep}]"
        else:
            invalid = [step for step in steps if not 0 < step <= self.boundary_timestep]
            expected = f"(0, {self.boundary_timestep}]"
        if invalid:
            raise ValueError(f"training.dmd.{name} contains timesteps {invalid} outside the {expert} interval {expected}.")

    def setup(self, resume_ckpt_path=None):
        super().setup(resume_ckpt_path=resume_ckpt_path)

        # Replace the generic RF scheduler after the base trainer has created
        # its three model roles.  All subsequent rollout/score operations use
        # the expert-aware bridge scheduler.
        scheduler_config = copy.deepcopy(self.dmd_config)
        scheduler_config["boundary_step"] = self.boundary_timestep
        scheduler_config["expert"] = self.expert
        scheduler_config["training_target"] = self.expert
        self.scheduler = Wan22DMDFlowMatchingScheduler(self.config, scheduler_config)
        self.denoising_sigmas = self._raw_steps_to_sigmas(self.denoising_step_list)

        self._validate_loaded_expert(self.model, "student", self.expert)
        self._validate_loaded_expert(self.fake_model, "fake", self.expert)
        self._validate_loaded_expert(self.teacher_model, "teacher", self.expert)

        if self.expert == "low_noise":
            self.high_prefix_model = self._build_high_prefix_model()
            self.high_prefix_sigmas = self._raw_steps_to_sigmas(self.high_prefix_steps)

        lower, upper = self.scheduler.expert_raw_timestep_bounds(self.expert)
        logger.info(
            "[train] {} expert={} boundary_raw={} boundary_sigma={:.6f} rollout_steps={} score_raw_range=[{}, {})",
            self.trainer_name,
            self.expert,
            self.boundary_timestep,
            self.scheduler.boundary_sigma,
            self.denoising_step_list,
            lower,
            upper,
        )
        if self.high_prefix_model is not None:
            logger.info(
                "[train] {} frozen high prefix steps={} path={}",
                self.trainer_name,
                self.high_prefix_steps,
                self.high_prefix_config["pretrained_model_name_or_path"],
            )

    def _raw_steps_to_sigmas(self, raw_steps):
        return self.scheduler.raw_timestep_to_sigma(
            torch.tensor(raw_steps, device=self.model.device, dtype=torch.float32),
            device=self.model.device,
            dtype=torch.float32,
        )

    @staticmethod
    def _validate_loaded_expert(model, role, expected):
        loaded = getattr(model, "expert", None)
        if loaded is None:
            return
        normalized = "high_noise" if loaded == "high" else "low_noise" if loaded == "low" else loaded
        if normalized != expected:
            raise ValueError(f"Wan2.2 {role} loaded expert={loaded!r}, expected {expected!r}.")

    def _build_high_prefix_model(self):
        if "pretrained_model_name_or_path" not in self.high_prefix_config:
            raise ValueError(
                "Low-expert Wan2.2 DMD requires "
                "training.dmd.high_prefix.pretrained_model_name_or_path."
            )

        prefix_config = copy.deepcopy(self.config)
        prefix_model_config = {
            key: copy.deepcopy(value)
            for key, value in self.model_config.items()
            if key not in {"fake", "teacher", "student"}
        }
        # Keep the concrete model adapter selected by the trainer.  Bernini
        # reuses this expert-aware rollout but must keep its own model adapter
        # when loading the frozen high expert.
        prefix_model_config["name"] = self.model_config["name"]
        prefix_model_config["expert"] = "high"
        prefix_model_config["pretrained_model_name_or_path"] = self.high_prefix_config["pretrained_model_name_or_path"]
        # The prefix is frozen and only participates in forward passes.  Do
        # not inherit the FP32 student-load dtype by default: that needlessly
        # doubles the resident weight memory of another 14B model.  A caller
        # can still override this through high_prefix.model below.
        prefix_model_config["transformer_param_dtype"] = self.high_prefix_config.get(
            "transformer_param_dtype",
            self.model_config.get("teacher", {}).get("transformer_param_dtype", "bf16"),
        )

        model_overrides = self.high_prefix_config.get("model", {})
        if not isinstance(model_overrides, Mapping):
            raise ValueError("training.dmd.high_prefix.model must be a mapping.")
        prefix_model_config.update(copy.deepcopy(model_overrides))

        checkpoint_path = self.high_prefix_config.get("checkpoint_path")
        consumed_checkpoint = False
        if checkpoint_path is not None:
            transformer_dir = self._resolve_transformer_checkpoint_dir(checkpoint_path)
            if transformer_dir is not None:
                prefix_model_config["pretrained_model_name_or_path"] = transformer_dir
                consumed_checkpoint = True

        # ``load_lora_for_infer`` reads inference.lora_config when it injects
        # the frozen adapter, so pass the prefix-specific LoRA shape through.
        prefix_config["model"] = prefix_model_config
        prefix_config.setdefault("inference", {})["lora_config"] = copy.deepcopy(
            self.high_prefix_config.get("lora", {})
        )

        model = build_model(prefix_config)
        model.load_components(transformer_only=True, reference_model=self.model)

        if checkpoint_path is not None and not consumed_checkpoint:
            self._load_frozen_prefix_state_dict(
                model,
                checkpoint_path,
                strict=bool(self.high_prefix_config.get("checkpoint_strict", True)),
            )

        lora_path = self.high_prefix_config.get("lora_path")
        if lora_path is not None:
            model.load_lora_for_infer(lora_path)

        model.denoiser_module().requires_grad_(False)
        model.denoiser_module().eval()
        apply_parallel(model, self.config)
        model.denoiser_module().eval()
        self._validate_loaded_expert(model, "high_prefix", "high_noise")
        return model

    @staticmethod
    def _resolve_transformer_checkpoint_dir(checkpoint_path) -> Optional[str]:
        checkpoint_path = os.fspath(checkpoint_path)
        if not os.path.isdir(checkpoint_path):
            return None
        candidates = (
            os.path.join(checkpoint_path, "student_consolidated", "transformer"),
            os.path.join(checkpoint_path, "student_consolidated"),
            os.path.join(checkpoint_path, "transformer"),
            checkpoint_path,
        )
        for candidate in candidates:
            if not os.path.isfile(os.path.join(candidate, "config.json")):
                continue
            has_weights = any(
                os.path.isfile(os.path.join(candidate, filename))
                for filename in (
                    "diffusion_pytorch_model.safetensors",
                    "diffusion_pytorch_model.safetensors.index.json",
                    "pytorch_model.bin",
                    "pytorch_model.bin.index.json",
                )
            )
            if has_weights:
                return candidate
        return None

    @staticmethod
    def _checkpoint_file(checkpoint_path):
        checkpoint_path = os.fspath(checkpoint_path)
        if os.path.isfile(checkpoint_path):
            return checkpoint_path
        for filename in (
            "model_state.pt",
            "consolidated.safetensors",
            "student_consolidated.safetensors",
            "distill_model.safetensors",
        ):
            candidate = os.path.join(checkpoint_path, filename)
            if os.path.isfile(candidate):
                return candidate
        raise RuntimeError(f"No supported frozen high-prefix checkpoint found at {checkpoint_path}.")

    @classmethod
    def _load_frozen_prefix_state_dict(cls, model, checkpoint_path, strict=True):
        checkpoint_file = cls._checkpoint_file(checkpoint_path)
        if checkpoint_file.endswith(".safetensors"):
            state = load_file(checkpoint_file, device="cpu")
        else:
            state = torch.load(checkpoint_file, map_location="cpu", weights_only=False)
        for key in ("generator_ema", "generator", "model", "state_dict"):
            if isinstance(state, Mapping) and isinstance(state.get(key), Mapping):
                state = state[key]
                break
        if not isinstance(state, Mapping):
            raise RuntimeError(f"Unsupported high-prefix checkpoint payload in {checkpoint_file}.")

        target_keys = set(model.denoiser_module().state_dict())
        direct = dict(state)
        stripped = {cls._strip_checkpoint_key(key): value for key, value in state.items()}
        selected = max((direct, stripped), key=lambda candidate: len(target_keys.intersection(candidate)))
        incompatible = model.denoiser_module().load_state_dict(selected, strict=strict)
        if not strict:
            if incompatible.missing_keys:
                logger.warning("Missing keys in frozen high-prefix checkpoint: {}", incompatible.missing_keys)
            if incompatible.unexpected_keys:
                logger.warning("Unexpected keys in frozen high-prefix checkpoint: {}", incompatible.unexpected_keys)
        logger.info("[train] loaded frozen high-prefix checkpoint {}", checkpoint_file)

    @staticmethod
    def _strip_checkpoint_key(key):
        prefixes = (
            "module.",
            "generator_ema.",
            "generator.",
            "model._fsdp_wrapped_module.",
            "model._checkpoint_wrapped_module.",
            "model._orig_mod.",
            "model.",
            "transformer.",
            "_fsdp_wrapped_module.",
            "_checkpoint_wrapped_module.",
            "_orig_mod.",
        )
        changed = True
        while changed:
            changed = False
            for prefix in prefixes:
                if key.startswith(prefix):
                    key = key[len(prefix) :]
                    changed = True
                    break
        return key

    def _sample_expert_score_sigma(self, batch_size):
        sigma = self.scheduler.sample_expert_sigma(
            batch_size,
            expert=self.expert,
            device=self.model.device,
            # Timesteps stay FP32 even when latent/model compute is BF16.
            # Quantizing the shifted Wan schedule changes the actual noise
            # level seen by all three DMD roles.
            dtype=torch.float32,
        )
        return broadcast_sequence_parallel_value(sigma)

    def _synced_noise(self, shape, *, dtype=None):
        noise = torch.randn(shape, device=self.model.device, dtype=dtype or self.running_dtype)
        return broadcast_sequence_parallel_value(noise)

    def _sigma_batch(self, sigma, batch_size):
        return sigma.to(device=self.model.device, dtype=torch.float32).reshape(1).expand(int(batch_size))

    def _predict_expert_endpoint(self, model, noisy_latent, sigma, condition, expert):
        flow = self._predict_velocity(model, noisy_latent, sigma, condition)
        endpoint = self.scheduler.flow_to_endpoint(
            flow_pred=flow,
            noisy_latent=noisy_latent,
            sigmas=sigma,
            expert=expert,
        )
        return flow, endpoint

    def _run_high_prefix(self, condition, latent_shape, initial_noise):
        if self.high_prefix_model is None:
            raise RuntimeError("The frozen high-prefix model has not been initialized.")

        xt = initial_noise
        endpoint = None
        self.high_prefix_model.denoiser_module().eval()
        with torch.no_grad():
            for idx, scalar_sigma in enumerate(self.high_prefix_sigmas):
                sigma = self._sigma_batch(scalar_sigma, latent_shape[0])
                _, endpoint = self._predict_expert_endpoint(
                    self.high_prefix_model,
                    xt,
                    sigma,
                    condition,
                    "high_noise",
                )
                if idx + 1 < len(self.high_prefix_sigmas):
                    next_sigma = self._sigma_batch(self.high_prefix_sigmas[idx + 1], latent_shape[0])
                    # The reference low-training prefix uses fresh Gaussian
                    # noise between its two distilled high-expert calls.
                    transition_noise = self._synced_noise(latent_shape)
                    xt = self.scheduler.add_noise_for_expert(
                        endpoint=endpoint,
                        noise=transition_noise,
                        sigmas=next_sigma,
                        expert="high_noise",
                    )
        return endpoint.detach()

    def run_back_simulation(self, condition, latent_shape, grad_enabled, xt=None):
        transformer = self.model.denoiser_module()
        if hasattr(transformer, "_forward_inference"):
            raise RuntimeError("wan22_a14b_dmd requires a bidirectional Wan2.2 expert.")

        if xt is None:
            initial_noise = self._synced_noise(latent_shape)
        else:
            initial_noise = xt

        if self.expert == "low_noise":
            xt = self._run_high_prefix(condition, latent_shape, initial_noise)
        else:
            xt = initial_noise

        exit_idx = self._sample_synced_int(0, len(self.denoising_sigmas))
        endpoint = None
        self.model.denoiser_module().train()
        for idx in range(exit_idx + 1):
            sigma = self._sigma_batch(self.denoising_sigmas[idx], latent_shape[0])
            context = torch.enable_grad if (grad_enabled and idx == exit_idx) else torch.no_grad
            with context():
                _, endpoint = self._predict_expert_endpoint(
                    self.model,
                    xt,
                    sigma,
                    condition,
                    self.expert,
                )

            if idx < exit_idx:
                next_sigma = self._sigma_batch(self.denoising_sigmas[idx + 1], latent_shape[0])
                if self.expert == "high_noise":
                    # High-expert training preserves the initial Gaussian in
                    # its consistency transition, matching the reference.
                    transition_noise = initial_noise
                else:
                    transition_noise = self._synced_noise(latent_shape)
                xt = self.scheduler.add_noise_for_expert(
                    endpoint=endpoint,
                    noise=transition_noise,
                    sigmas=next_sigma,
                    expert=self.expert,
                )

        return endpoint.to(dtype=self.running_dtype)

    def forward_loss(self, latent_shape, conditions, stage):
        condition, negative_condition = conditions
        generated = self.run_back_simulation(
            condition,
            latent_shape,
            grad_enabled=stage != "fake",
        )

        sigma = self._sample_expert_score_sigma(latent_shape[0])
        noise = self._synced_noise(latent_shape)
        with torch.no_grad():
            renoised_xt = self.scheduler.add_noise_for_expert(
                endpoint=generated.detach(),
                noise=noise,
                sigmas=sigma,
                expert=self.expert,
            )

        if stage == "fake":
            self.fake_model.denoiser_module().train()
            velocity_fake = self._predict_velocity(self.fake_model, renoised_xt, sigma, condition)
            predicted_training_target = self.scheduler.flow_to_training_target(
                flow_pred=velocity_fake,
                noisy_latent=renoised_xt,
                sigmas=sigma,
                expert=self.expert,
            )
            return F.mse_loss(predicted_training_target.float(), generated.detach().float(), reduction="mean")

        if stage != "student":
            raise ValueError(f"Unsupported {self.trainer_name} training stage: {stage!r}.")

        with torch.no_grad():
            self.fake_model.denoiser_module().eval()
            self.teacher_model.denoiser_module().eval()
            velocity_fake = self._predict_velocity(self.fake_model, renoised_xt, sigma, condition)
            velocity_teacher = self._predict_teacher_velocity(
                renoised_xt,
                sigma,
                condition,
                negative_condition,
            )
            endpoint_fake = self.scheduler.flow_to_endpoint(
                flow_pred=velocity_fake,
                noisy_latent=renoised_xt,
                sigmas=sigma,
                expert=self.expert,
            )
            endpoint_teacher = self.scheduler.flow_to_endpoint(
                flow_pred=velocity_teacher,
                noisy_latent=renoised_xt,
                sigmas=sigma,
                expert=self.expert,
            )

        return self._dmd_loss(generated, endpoint_fake, endpoint_teacher)
